import Link from 'next/link'
import './globals.css'

// 웹사이트 제목을 바꾸고 싶다면 이 부분을 수정해주면 된다.
export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by Ag',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          <li><Link href="/read/1">html</Link></li>
          <li><Link href="/read/2">css</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete"/></li>
        </ul>
      </body>
    </html>
  )
}
