import Link from 'next/link'
import './globals.css'
import { Control } from './Control';
// import { useEffect, useState } from 'react'

// 웹사이트 제목을 바꾸고 싶다면 이 부분을 수정해주면 된다.
// meta 컴포넌트는 서버 컴포넌트에서만 사용이 된다.

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by Ag',
}

/* await 라는 promise 문법을 사용하기 위해서 async를 써준다. */
export default async function RootLayout({ children }) {
  // const [topics, setTopics] = useState([]);
  /*
  useEffect(()=>{
    fetch('http://localhost:9999/topics')
    .then(resp=>resp.json())
    .then(result=>{
      setTopics(result);
    });
  }, []);
  */
  const resp = await fetch('http://localhost:9999/topics') 
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
